export const presets = [
  {
    gameMode: 'Standard',
    leadercap: false,
    weight: 100,
    pointsPerEvolve: 1,
    pointsPerPowerup: 1,
    pointsPerKill: 20,
    pointsPerReward: 5,
  },
  {
    gameMode: 'Lets Be Friends',
    leadercap: false,
    weight: 2,
    pointsPerKill: -200,
    orbOnDeathPercent: 0,
    antifeed1: false,
    antifeed2: false,
    calcRoundRewards: false,
    preventBadKills: false,
    guide: ['Game Mode - Lets Be Friends', '-200 Points Per Kill', 'No Death Orbs'],
  },
  {
    gameMode: 'Indiana Jones',
    leadercap: false,
    weight: 30,
    pointsPerEvolve: 0,
    pointsPerPowerup: 0,
    pointsPerKill: 1,
    pointsPerReward: 100,
    pointsPerOrb: 0,
    baseSpeed: 4,
    cameraSize: 2.5,
    hideMap: true,
    orbOnDeathPercent: 0,
    guide: ['Game Mode - Indiana Jones', '+100 Points Per Treasure Found'],
  },
  {
    gameMode: 'Mix Game 1',
    leadercap: false,
    weight: 1,
    pointsPerEvolve: 1,
    pointsPerPowerup: 1,
    pointsPerKill: 1,
    pointsPerReward: 50,
    pointsPerOrb: 1,
    isOmit: true,
  },
  {
    gameMode: 'Mix Game 2',
    leadercap: false,
    weight: 1,
    pointsPerEvolve: 10,
    pointsPerKill: 200,
    pointsPerReward: 20,
    isOmit: true,
  },
  {
    gameMode: 'Deathmatch',
    leadercap: false,
    weight: 30,
    pointsPerKill: 200,
    orbOnDeathPercent: 0,
    pointsPerEvolve: 0,
    pointsPerPowerup: 0,
    pointsPerReward: 1,
    pointsPerOrb: 0,
    baseSpeed: 3.5,
    antifeed1: false,
    // dynamicDecayPower: true,
    // decayPowerPerMaxEvolvedClients: 0.2,
    guide: ['Game Mode - Deathmatch', '+300 Points Per Kill (Per Evolve)', 'No Death Orbs', 'Faster Decay'],
  },
  {
    gameMode: 'Evolution',
    leadercap: false,
    weight: 1,
    pointsPerKill: 0,
    pointsPerEvolve: 1,
    pointsPerPowerup: 0,
    pointsPerReward: 0,
    pointsPerOrb: 0,
    orbOnDeathPercent: 0,
    guide: ['Game Mode - Evolution', '+1 Points Per Evolution'],
  },
  {
    gameMode: 'Classic Evolution',
    leadercap: false,
    weight: 10,
    pointsPerEvolve: 10,
    pointsPerPowerup: 0,
    pointsPerReward: 0,
    pointsPerOrb: 0,
    guide: ['Game Mode - Evolution', '+10 Points Per Evolution'],
  },
  {
    gameMode: 'Orb Master',
    leadercap: false,
    weight: 10,
    // orbOnDeathPercent: 25,
    orbTimeoutSeconds: 3,
    pointsPerOrb: 300,
    pointsPerEvolve: 0,
    pointsPerReward: 0,
    pointsPerPowerup: 1,
    pointsPerKill: 0,
    orbCutoffSeconds: 0,
    guide: [
      'Game Mode - Orb Master',
      '+200 Points Per Orb Pickup',
      'No Points Per Kill, Evolve, etc.',
      'Orbs Last Until End of Round',
    ],
  },
  {
    gameMode: 'Sprite Leader',
    leadercap: false,
    weight: 10,
    spritesPerClientCount: 40,
    // decayPower: 7,
    avatarDecayPower0: 2,
    avatarDecayPower1: 2 * (7 / 1.4),
    avatarDecayPower2: 2 * (7 / 1.4),
    avatarSpeedMultiplier0: 1.2,
    avatarSpeedMultiplier1: 1,
    avatarSpeedMultiplier2: 0.85,
    // decayPowerPerMaxEvolvedClients: 2,
    pointsPerEvolve: 0,
    pointsPerPowerup: 1,
    pointsPerReward: 0,
    pointsPerKill: 0,
    pointsPerOrb: 0,
    immunitySeconds: 2,
    orbOnDeathPercent: 0,
    guide: [
      'Game Mode - Sprite Leader',
      '+3 Sprites Per Client',
      'No Points Per Kill, Evolve, etc.',
      'No Orbs',
      'Faster Decay',
      'Longer Immunity',
    ],
  },
  {
    gameMode: 'Fast Drake',
    leadercap: false,
    weight: 20,
    avatarDecayPower0: 1,
    avatarDecayPower1: 1,
    avatarDecayPower2: 1,
    avatarSpeedMultiplier2: 1.5,
    decayPower: 0.3,
    decayPowerPerMaxEvolvedClients: 25,
    immunitySeconds: 10,
    orbOnDeathPercent: 0,
    spritesPerClientCount: 20,
    level2forced: true,
    guide: ['Game Mode - Fast Drake', '+50% Speed as Black Drake', 'Faster Decay', 'Longer Immunity'],
  },
  {
    gameMode: 'Bird Eye',
    leadercap: false,
    weight: 10,
    cameraSize: 6,
    baseSpeed: 3.5,
    decayPower: 2.8,
    pointsPerKill: 500,
    level2forced: true,
    guide: ['Game Mode - Bird Eye', 'Faster Movement', 'Faster Decay'],
  },
  {
    gameMode: 'Friendly Reverse',
    leadercap: false,
    weight: 10,
    pointsPerKill: -200,
    orbOnDeathPercent: 0,
    antifeed1: false,
    antifeed2: false,
    pointsPerEvolve: 25,
    avatarSpeedMultiplier0: 1,
    avatarSpeedMultiplier1: 1,
    avatarSpeedMultiplier2: 1,
    decayPower: -3,
    dynamicDecayPower: false,
    avatarDecayPower0: 4,
    avatarDecayPower1: 3,
    avatarDecayPower2: 2,
    spriteXpMultiplier: -1,
    spritesPerClientCount: 10,
    preventBadKills: false,
    guide: [
      'Game Mode - Friendly Reverse',
      '-200 Points Per Kill (Per Evolve)',
      '+25 Points Per Evolve',
      'Reverse Evolution',
      'No Orbs',
    ],
  },
  {
    gameMode: 'Reverse Evolve',
    leadercap: false,
    weight: 1,
    startAvatar: 2,
    decayPower: -1,
    antifeed1: false,
    antifeed2: false,
    dynamicDecayPower: false,
    decayPowerPerMaxEvolvedClients: 2,
    avatarDecayPower0: 4,
    avatarDecayPower1: 3,
    avatarDecayPower2: 2,
    // avatarDecayPower0: 1.5,
    // avatarDecayPower1: 2.5,
    // avatarDecayPower2: 3,
    spriteXpMultiplier: -2,
    // avatarDirection: -1,
    guide: ['Game Mode - Reverse Evolve', 'Evolution is reversed'],
  },
  {
    gameMode: 'Classic Marco Polo',
    leadercap: false,
    weight: 30,
    cameraSize: 2,
    baseSpeed: 2.5,
    decayPower: 2,
    avatarSpeedMultiplier0: 1,
    avatarSpeedMultiplier1: 1,
    avatarSpeedMultiplier2: 1,
    // pointsPerReward: 20,
    hideMap: true,
    // level2forced: true,
    guide: ['Game Mode - Classic Marco Polo', 'Zoomed in + no map', 'Faster Decay'],
  },
  {
    gameMode: 'Marco Polo',
    leadercap: false,
    weight: 20,
    cameraSize: 2,
    baseSpeed: 2.5,
    decayPower: 2,
    avatarSpeedMultiplier0: 1,
    avatarSpeedMultiplier1: 1,
    avatarSpeedMultiplier2: 1,
    pointsPerReward: 20,
    hideMap: true,
    level2forced: true,
    guide: ['Game Mode - Marco Polo', 'Zoomed in + no map', 'Sprites Change Camera'],
  },
  {
    gameMode: 'Leadercap',
    leadercap: true,
    weight: 1,
    guide: ['Game Mode - Leadercap', 'Kill the last round leader', 'Leader -20% Speed', 'Leader 75% Death Orb'],
  },
  {
    gameMode: 'Sticky Mode',
    leadercap: false,
    weight: 1,
    stickyIslands: true,
    colliderBuffer: 0,
    pointsPerKill: 50,
    pointsPerOrb: 100,
    isOmit: true,
    guide: ['Game Mode - Sticky Mode', 'Sticky islands'],
  },
  {
    gameMode: 'Sprite Juice',
    leadercap: false,
    weight: 1,
    // spritesPerClientCount: 1,
    spritesStartCount: 25,
    spritesTotal: 25,
    decayPowerPerMaxEvolvedClients: 2,
    // antifeed1: false,
    // isOmit: true,
    guide: [
      'Game Mode - Sprite Juice',
      // 'Sprites have side effects!',
      'Purple - Increase Decay',
      'Pink - Decrease Speed',
      'Yellow - Increase Speed',
      'Blue - Shield',
    ],
  },
  // {
  //   gameMode: 'Friendly Pandamonium',
  //   weight: 1,
  //   isOmit: true,
  //   guide: [
  //     'Game Mode - Friendly Pandamonium',
  //     'Beware the Panda'
  //   ]
  // },
  {
    gameMode: 'Pandamonium',
    weight: 2,
    isOmit: true,
    isBattleRoyale: true,
    avatarSpeedMultiplier0: 1,
    avatarSpeedMultiplier1: 1,
    avatarSpeedMultiplier2: 1.4,
    avatarTouchDistance2: 1,
    damagerPerTouch: 500,
    guide: ['Game Mode - Pandamonium', 'Beware the Panda'],
  },
  {
    gameMode: 'Hayai',
    leadercap: false,
    weight: 2,
    level2forced: true,
    decayPower: 3.6,
    isOmit: true,
    guide: ['Game Mode - Hayai', 'You feel energy growing around you...'],
  },
  {
    gameMode: 'Storm Cuddle',
    leadercap: false,
    weight: 10,
    fortnight: true,
    isOmit: true,
  },
];
